"const" @keyword
"action" @keyword
"apply" @keyword
"bool" @type
"control" @keyword
"default" @keyword
"else" @keyword
"enum" @keyword
"error" @type
"exit" @keyword
"extern" @keyword
"false" @constant
"header" @keyword
"header_union" @keyword
"if" @keyword
"in" @keyword
"inout" @keyword
"int" @type
"match_kind" @keyword
"out" @keyword
"package" @keyword
"parser" @keyword
"return" @keyword
"select" @keyword
"state" @keyword
"struct" @keyword
"table" @keyword
"this" @keyword
"transition" @keyword
"true" @constant
"tuple" @type
"typedef" @keyword
"varbit" @type

(bit_type) @type
(varbit_type) @type
(number) @number
(string_literal) @string
(bool) @constant
(annotation) @attribute
(comment) @comment
